version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.12.6


    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout

      - restore_cache:
          key: ogpserve2-mod-{{ checksum "go.sum" }}

      - run:
          name: go mod download
          command: go mod download

      - save_cache:
          key: ogpserve2-mod-{{ checksum "go.sum" }}
          paths:
            - "~/go/pkg/mod/cache"

      - run: mkdir -p $TEST_RESULTS
      - run: go vet ./...
      - run: go test -race ./...

      - store_artifacts:
          path: /tmp/test-results

      - store_test_results:
          path: /tmp/test-results
